// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: pod/v1/pod.proto

package pod

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EciService_SavePod_FullMethodName = "/pod.EciService/SavePod"
)

// EciServiceClient is the client API for EciService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EciServiceClient interface {
	SavePod(ctx context.Context, in *EciPod, opts ...grpc.CallOption) (*SavePodResp, error)
}

type eciServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEciServiceClient(cc grpc.ClientConnInterface) EciServiceClient {
	return &eciServiceClient{cc}
}

func (c *eciServiceClient) SavePod(ctx context.Context, in *EciPod, opts ...grpc.CallOption) (*SavePodResp, error) {
	out := new(SavePodResp)
	err := c.cc.Invoke(ctx, EciService_SavePod_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EciServiceServer is the server API for EciService service.
// All implementations must embed UnimplementedEciServiceServer
// for forward compatibility
type EciServiceServer interface {
	SavePod(context.Context, *EciPod) (*SavePodResp, error)
	mustEmbedUnimplementedEciServiceServer()
}

// UnimplementedEciServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEciServiceServer struct {
}

func (UnimplementedEciServiceServer) SavePod(context.Context, *EciPod) (*SavePodResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SavePod not implemented")
}
func (UnimplementedEciServiceServer) mustEmbedUnimplementedEciServiceServer() {}

// UnsafeEciServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EciServiceServer will
// result in compilation errors.
type UnsafeEciServiceServer interface {
	mustEmbedUnimplementedEciServiceServer()
}

func RegisterEciServiceServer(s grpc.ServiceRegistrar, srv EciServiceServer) {
	s.RegisterService(&EciService_ServiceDesc, srv)
}

func _EciService_SavePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EciPod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EciServiceServer).SavePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EciService_SavePod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EciServiceServer).SavePod(ctx, req.(*EciPod))
	}
	return interceptor(ctx, in, info, handler)
}

// EciService_ServiceDesc is the grpc.ServiceDesc for EciService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EciService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pod.EciService",
	HandlerType: (*EciServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SavePod",
			Handler:    _EciService_SavePod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pod/v1/pod.proto",
}
